There is no more -job-file argument
hashicorp/levant pull request #434
Opened 2021-11-15 21:37 UTC by ernetas

There is no more -job-file argument, so this help text is misleading.

2021-11-15 21:37 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/levant?pullRequest=434)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/levant?pullRequest=434)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/levant?pullRequest=434).</sub>

2021-11-24 09:29 UTC, jrasell requested changes
Thanks for spotting this. I have made a suggestion to clarify the helper and use language similar to Nomad.

2021-11-24 09:29 UTC, jrasell commented on command/plan.go
> +    flag multiple times to supply multiple var-files.
```suggestion
    Path to a file containing user variables used when rendering the job
    template. You can repeat this flag multiple times to supply multiple
    var-files. Defaults to levant.(json|yaml|yml|tf).
```

2021-11-24 09:29 UTC, jrasell commented on command/deploy.go
> +    flag multiple times to supply multiple var-files.
```suggestion
    Path to a file containing user variables used when rendering the job
    template. You can repeat this flag multiple times to supply multiple
    var-files. Defaults to levant.(json|yaml|yml|tf).
```

2023-05-22 23:24 UTC, angrycub approved these changes
:+1:

2023-05-22 23:27 UTC, merged